
/*
 * ================================================================
 * COMPREHENSIVE JSON SERIALIZER
 * Generated by Claude (Anthropic AI Assistant)
 *
 * This serializer automatically handles all C++ types including:
 * - Basic types (int, string, bool, double, etc.)
 * - Vectors (single, nested, triple-nested)
 * - Maps and complex key-value structures
 * - Optional types with null handling
 * - Tuples as JSON arrays
 * - Mixed complex types and combinations
 *
 * Usage: meta::json::serialize(your_vector_of_objects)
 * ================================================================
 */

namespace demo
{
struct ComplexRow
{
    int id;
    std::string name;
    std::vector<int> scores;       // Simple vector
    std::vector<std::string> tags; // Vector of strings

    //  has to be hand wired into .meta
    //  clang does not create nested templares in hdr files

    std::vector<std::vector<int>> matrix; // 2D matrix

    std::vector<std::vector<std::string>> categories; // Nested string arrays
};
} // namespace demo
