#!/usr/bin/env python3
"""
JSON Slideshow to PDF Converter
Converts JSON slideshow data to a professional PDF presentation.

Generated by Claude - AI Assistant by Anthropic
https://claude.ai

This script reads a JSON slideshow structure and generates a professional PDF
presentation with proper formatting, syntax highlighting, and multiple slide types.
"""

import json
import sys
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.platypus import Table, TableStyle, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

class HeaderFooterCanvas(canvas.Canvas):
    """Custom canvas with header showing 'Generated by Claude'"""
    
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []
        
    def showPage(self):
        """Override to add header to each page"""
        self.pages.append(dict(self.__dict__))
        self._startPage()
        
    def save(self):
        """Add header to all pages before saving"""
        page_count = len(self.pages)
        for page_num in range(page_count):
            self.__dict__.update(self.pages[page_num])
            self.draw_header(page_num + 1, page_count)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)
        
    def draw_header(self, page_num, total_pages):
        """Draw header with 'Generated by Claude'"""
        self.saveState()
        
        # Header text
        self.setFont('Helvetica', 8)
        self.setFillColor(HexColor('#7f8c8d'))
        
        # Right side: Generated by Claude
        self.drawRightString(
            self._pagesize[0] - 0.8*inch, 
            self._pagesize[1] - 0.4*inch, 
            "Generated by Claude"
        )
        
        # Left side: Page number
        self.drawString(
            0.8*inch, 
            self._pagesize[1] - 0.4*inch, 
            f"Page {page_num} of {total_pages}"
        )
        
        self.restoreState()

class SlideshowPDFGenerator:
    def __init__(self, json_data):
        self.data = json_data
        self.slideshow = json_data['slideshow']
        self.styling = self.slideshow.get('styling', {})
        self.story = []
        self.setup_styles()
    
    def setup_styles(self):
        """Setup PDF styles based on JSON styling configuration"""
        self.styles = getSampleStyleSheet()
        
        # Get colors from JSON or use defaults
        colors = self.styling.get('colors', {})
        primary = colors.get('primary', '#2c3e50')
        secondary = colors.get('secondary', '#3498db')
        code_bg = colors.get('code_bg', '#f8f8f2')
        code_text = colors.get('code_text', '#272822')
        terminal_bg = colors.get('terminal_bg', '#0c0c0c')
        terminal_text = colors.get('terminal_text', '#00ff41')
        
        # Debug: Print the colors being used
        print(f"Code background: {code_bg}")
        print(f"Code text: {code_text}")
        print(f"Terminal background: {terminal_bg}")
        print(f"Terminal text: {terminal_text}")
        
        # Title style
        if 'CustomTitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomTitle',
                parent=self.styles['Title'],
                fontSize=24,
                spaceAfter=20,
                textColor=HexColor(primary),
                alignment=TA_CENTER,
                fontName='Helvetica-Bold'
            ))
        
        # Subtitle style
        if 'CustomSubtitle' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomSubtitle',
                parent=self.styles['Normal'],
                fontSize=16,
                spaceAfter=15,
                textColor=HexColor(secondary),
                alignment=TA_CENTER,
                fontName='Helvetica-Oblique'
            ))
        
        # Code style - using JSON colors
        if 'CustomCode' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomCode',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName='Courier',
                textColor=HexColor(code_text),
                backColor=HexColor(code_bg),
                leftIndent=10,
                rightIndent=10,
                spaceBefore=10,
                spaceAfter=10,
                borderPadding=10
            ))
        
        # Terminal/Output style - using JSON colors
        if 'CustomOutput' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomOutput',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName='Courier',
                textColor=HexColor(terminal_text),
                backColor=HexColor(terminal_bg),
                leftIndent=10,
                rightIndent=10,
                spaceBefore=10,
                spaceAfter=10,
                borderPadding=10
            ))

        # Output style - using JSON colors
        # Terminal/Output style - using JSON colors
        if 'Output' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='Output',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName='Courier',
                textColor=HexColor(terminal_text),
                backColor=HexColor(terminal_bg),
                leftIndent=10,
                rightIndent=10,
                spaceBefore=10,
                spaceAfter=10,
                borderPadding=10
            ))

        # Output style - using JSON colors
        # Terminal/Output style - using JSON colors
        if 'CustomOutput' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomOutput',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName='Courier',
                textColor=HexColor(terminal_text),
                backColor=HexColor(terminal_bg),
                leftIndent=10,
                rightIndent=10,
                spaceBefore=10,
                spaceAfter=10,
                borderPadding=10
            ))



            
        # Feature list style
        if 'CustomFeature' not in self.styles:
            self.styles.add(ParagraphStyle(
                name='CustomFeature',
                parent=self.styles['Normal'],
                fontSize=11,
                spaceAfter=5,
                leftIndent=20,
                bulletIndent=10
            ))
    
    def apply_syntax_highlighting(self, code_text):
        """Apply basic C++ syntax highlighting to code text"""
        
        # Get colors from JSON
        colors = self.styling.get('colors', {})
        keyword_color = colors.get('keyword', '#0033b3')
        type_color = colors.get('type', '#0080ff') 
        string_color = colors.get('string', '#067d17')
        comment_color = colors.get('comment', '#8c8c8c')
        function_color = colors.get('function', '#795548')
        
        # For now, just return the original code without highlighting
        # to avoid HTML parsing issues
        return code_text
    
    def create_title_page(self, slide):
        """Create main title page"""
        title = slide.get('title', '')
        subtitle = slide.get('subtitle', '')
        content = slide.get('content', {})
        
        # Add some vertical space
        self.story.append(Spacer(1, 2*inch))
        
        # Main title - larger
        title_style = ParagraphStyle(
            'MainTitle',
            parent=self.styles['Title'],
            fontSize=36,
            spaceAfter=30,
            textColor=HexColor('#2c3e50'),
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        self.story.append(Paragraph(title, title_style))
        
        # Subtitle
        if subtitle:
            subtitle_style = ParagraphStyle(
                'MainSubtitle',
                parent=self.styles['Normal'],
                fontSize=24,
                spaceAfter=40,
                textColor=HexColor('#3498db'),
                alignment=TA_CENTER,
                fontName='Helvetica'
            )
            self.story.append(Paragraph(subtitle, subtitle_style))
        
        # Add more space
        self.story.append(Spacer(1, 1*inch))
        
        # Author and date info
        if 'author' in content:
            author_style = ParagraphStyle(
                'Author',
                parent=self.styles['Normal'],
                fontSize=16,
                spaceAfter=10,
                textColor=HexColor('#7f8c8d'),
                alignment=TA_CENTER,
                fontName='Helvetica'
            )
            self.story.append(Paragraph(content['author'], author_style))
        
        if 'date' in content:
            date_style = ParagraphStyle(
                'Date',
                parent=self.styles['Normal'],
                fontSize=14,
                spaceAfter=10,
                textColor=HexColor('#7f8c8d'),
                alignment=TA_CENTER,
                fontName='Helvetica'
            )
            self.story.append(Paragraph(content['date'], date_style))

            
    def create_multi_output_page(self, slide):
        """Create multi-output slide with sections"""
        title = slide.get('title', '')
        subtitle = slide.get('subtitle', '')
        content = slide.get('content', {})

        print(slide)
        
        # Title and subtitle
        self.story.append(Paragraph(title, self.styles['CustomTitle']))
        if subtitle:
            self.story.append(Paragraph(subtitle, self.styles['CustomSubtitle']))
        
        self.story.append(Spacer(1, 0.2*inch))
        
        # Sections
        if 'sections' in content:
            for section in content['sections']:
                # Section name
                section_style = ParagraphStyle(
                    'SectionName',
                    parent=self.styles['Normal'],
                    fontSize=14,
                    textColor=HexColor('#2c3e50'),
                    fontName='Helvetica-Bold',
                    spaceBefore=15,
                    spaceAfter=5
                )
                self.story.append(Paragraph(section['name'], section_style))
                
                # Section output
                output_text = section['output'].replace('\n', '<br/>')
                self.story.append(Paragraph(output_text, self.styles['Output']))
    

    def create_title_slide(self, slide):
        """Create title/intro slide"""
        title = slide.get('title', '')
        subtitle = slide.get('subtitle', '')
        content = slide.get('content', {})
        
        # Title
        self.story.append(Paragraph(title, self.styles['CustomTitle']))
        self.story.append(Spacer(1, 0.3*inch))
        
        # Subtitle
        if subtitle:
            self.story.append(Paragraph(subtitle, self.styles['CustomSubtitle']))
            self.story.append(Spacer(1, 0.2*inch))
        
        # Description
        if 'description' in content:
            desc_style = ParagraphStyle(
                'Description',
                parent=self.styles['Normal'],
                fontSize=12,
                spaceAfter=15,
                alignment=TA_CENTER
            )
            self.story.append(Paragraph(content['description'], desc_style))
            self.story.append(Spacer(1, 0.2*inch))
        
        # Features list
        if 'features' in content:
            for feature in content['features']:
                self.story.append(Paragraph(f"• {feature}", self.styles['CustomFeature']))
        
        # Tagline
        if 'tagline' in content:
            tagline_style = ParagraphStyle(
                'Tagline',
                parent=self.styles['Normal'],
                fontSize=14,
                textColor=HexColor('#e74c3c'),
                alignment=TA_CENTER,
                fontName='Helvetica-BoldOblique',
                spaceBefore=20
            )
            self.story.append(Spacer(1, 0.3*inch))
            self.story.append(Paragraph(f'"{content["tagline"]}"', tagline_style))
    
    def create_code_slide(self, slide):
        """Create code slide"""
        title = slide.get('title', '')
        subtitle = slide.get('subtitle', '')
        content = slide.get('content', {})
        
        # Title and subtitle
        self.story.append(Paragraph(title, self.styles['CustomTitle']))
        if subtitle:
            self.story.append(Paragraph(subtitle, self.styles['CustomSubtitle']))
        
        self.story.append(Spacer(1, 0.2*inch))
        
        # Code block with light background and syntax highlighting
        if 'code' in content:
            # Get background color from JSON
            colors = self.styling.get('colors', {})
            code_bg = colors.get('code_bg', '#f8f8f2') 
            
            #print(f"Creating code block with background: {code_bg}")
            
            # Apply syntax highlighting
            code_text = content['code']
            if content.get('highlight', False):
                highlighted_code = self.apply_syntax_highlighting(code_text)
            else:
                highlighted_code = code_text
            
            # Create paragraph with dark text and syntax highlighting
            code_style = ParagraphStyle(
                'CodeWithBG',
                parent=self.styles['Normal'],
                fontSize=10,
                fontName='Courier',
                textColor=HexColor('#000000'),  # Default dark text
                leftIndent=0,
                rightIndent=0,
                spaceBefore=0,
                spaceAfter=0,
                leading=14  # Slightly more line spacing for readability
            )
            
            lines = highlighted_code.split('\n')
            formatted_code = '<br/>'.join(lines)
            
            code_para = Paragraph(formatted_code, code_style)
            
            # Use table for light background
            code_table = Table([[code_para]], colWidths=[7*inch])
            code_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), HexColor(code_bg)),  # Light background
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('LEFTPADDING', (0, 0), (-1, -1), 15),
                ('RIGHTPADDING', (0, 0), (-1, -1), 15),
                ('TOPPADDING', (0, 0), (-1, -1), 15),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 15),
                ('GRID', (0, 0), (-1, -1), 1, HexColor('#cccccc')),  # Light border
            ]))
            
            self.story.append(code_table)
        
        # Note
        if 'note' in content:
            note_style = ParagraphStyle(
                'Note',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=HexColor('#7f8c8d'),
                alignment=TA_CENTER,
                fontName='Helvetica-Oblique',
                spaceBefore=15
            )
            self.story.append(Paragraph(f"Note: {content['note']}", note_style))
    
    def create_terminal_slide(self, slide):
        """Create terminal/command slide with different styling"""
        title = slide.get('title', '')
        subtitle = slide.get('subtitle', '')
        content = slide.get('content', {})
        
        # Title and subtitle
        self.story.append(Paragraph(title, self.styles['CustomTitle']))
        if subtitle:
            self.story.append(Paragraph(subtitle, self.styles['CustomSubtitle']))
        
        self.story.append(Spacer(1, 0.2*inch))
        
        # Commands and outputs
        if 'commands' in content:
            for command in content['commands']:
                # Command prompt
                if 'prompt' in command:
                    prompt_style = ParagraphStyle(
                        'Prompt',
                        parent=self.styles['Normal'],
                        fontSize=10,
                        fontName='Courier',
                        textColor=HexColor('#00ff41'),
                        backColor=HexColor('#0c0c0c'),
                        leftIndent=10,
                        rightIndent=10,
                        spaceBefore=5,
                        spaceAfter=5,
                        borderPadding=8
                    )
                    self.story.append(Paragraph(command['prompt'], prompt_style))
                
                # Command output
                if 'output' in command:
                    output_text = command['output'].replace('\n', '<br/>')
                    self.story.append(Paragraph(output_text, self.styles['CustomOutput']))
        
        # Note
        if 'note' in content:
            note_style = ParagraphStyle(
                'Note',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=HexColor('#7f8c8d'),
                alignment=TA_CENTER,
                fontName='Helvetica-Oblique',
                spaceBefore=15
            )
            self.story.append(Paragraph(f"Note: {content['note']}", note_style))
    
    def generate_pdf(self, output_filename):
        """Generate the PDF from JSON data"""
        # Setup document with custom canvas
        page_size = A4 if self.styling.get('layout', {}).get('page_size') == 'A4' else letter
        
        # Handle landscape orientation
        layout = self.styling.get('layout', {})
        if layout.get('page_size') == 'A4_landscape':
            from reportlab.lib.pagesizes import landscape
            page_size = landscape(A4)
        
        doc = SimpleDocTemplate(
            output_filename,
            pagesize=page_size,
            topMargin=1.0*inch,  # Increased for header space
            bottomMargin=0.8*inch,
            leftMargin=0.8*inch,
            rightMargin=0.8*inch,
            canvasmaker=HeaderFooterCanvas  # Use our custom canvas
        )
        
        # Process each slide
        slides = self.slideshow.get('slides', [])
        for i, slide in enumerate(slides):
            slide_type = slide.get('type', 'code')
            print(slide_type)
            # Create slide based on type
            if slide_type == 'title':
                self.create_title_page(slide)
            if slide_type == 'multi-output':
                self.create_multi_output_page(slide)
            elif slide_type == 'intro':
                self.create_title_slide(slide)
            elif slide_type == 'code':
                self.create_code_slide(slide)
            elif slide_type == 'terminal':
                self.create_terminal_slide(slide)
            else:
                # Default to code slide
                self.create_code_slide(slide)
            
            # Add page break except for last slide
            if i < len(slides) - 1:
                self.story.append(PageBreak())
        
        # Build PDF
        doc.build(self.story)
        print(f"PDF generated successfully: {output_filename}")

def main():
    if len(sys.argv) < 3:
        print("Usage: python json_to_pdf.py <output.pdf> <input1.json> [input2.json] [input3.json] ...")
        print("Example: python json_to_pdf.py presentation.pdf intro.json demo.json conclusion.json")
        sys.exit(1)
    
    output_file = sys.argv[1]
    input_files = sys.argv[2:]
    
    # Validate arguments
    if not output_file.endswith('.pdf'):
        print(f"Error: Output file '{output_file}' should end with .pdf")
        sys.exit(1)
    
    for input_file in input_files:
        if not input_file.endswith('.json'):
            print(f"Error: Input file '{input_file}' should be a JSON file (.json)")
            sys.exit(1)
    
    print(f"Combining {len(input_files)} JSON files into {output_file}")
    
    try:
        # Load and combine all JSON files
        combined_slides = []
        combined_styling = {}
        slideshow_info = {}
        
        for i, input_file in enumerate(input_files):
            print(f"Loading {input_file}...")
            
            with open(input_file, 'r', encoding='utf-8') as f:
                json_data = json.load(f)
            
            slideshow = json_data['slideshow']
            
            # Use info from first file for overall presentation
            if i == 0:
                slideshow_info = {
                    'title': slideshow.get('title', 'Combined Presentation'),
                    'author': slideshow.get('author', 'Author'),
                    'date': slideshow.get('date', '2025-09-20'),
                    'theme': slideshow.get('theme', 'modern')
                }
                combined_styling = slideshow.get('styling', {})
            
            # Add slides with updated IDs
            slides = slideshow.get('slides', [])
            for slide in slides:
                # Update slide ID to be unique across all files
                slide['id'] = len(combined_slides) + 1
                combined_slides.append(slide)
        
        # Create combined JSON structure
        combined_json = {
            'slideshow': {
                **slideshow_info,
                'slides': combined_slides,
                'styling': combined_styling
            }
        }
        
        print(f"Combined {len(combined_slides)} slides total")
        
        # Generate PDF
        generator = SlideshowPDFGenerator(combined_json)
        generator.generate_pdf(output_file)
        
    except FileNotFoundError as e:
        print(f"Error: Input file not found: {e}")
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON: {e}")
    except Exception as e:
        print(f"Error generating PDF: {e}")

if __name__ == "__main__":
    # Check dependencies
    try:
        import reportlab
    except ImportError:
        print("Error: reportlab library is required.")
        print("Install it with: pip install reportlab")
        sys.exit(1)
    
    main()

# Example usage:
# python json_to_pdf.py slideshow.json presentation.pdf

